### ISSUE TITLE
Let the user specify the full version

### ISSUE THREAD

**Issue by robross0606** [juliogonzalez/nexus-oss-rpms#39]
This only supports the simple "2" and "3" parameters but doesn't even pull the latest version since a specific version is hard coded in the spec file.  Why not simply let the user specify the full version they want from the command line?

**Comment by juliogonzalez** [comment]
@robross0606 because then you can't keep track of the changelog, and because different versions can require different stuff (for example in the past there was a change for the JDK version required, or I add and remove patches when needed).

I try to keep the SPECs up to date, and then you can switch to the tag you want to build whatever you need.

But if there is a new version, adding it to the repository is something almost everyone can do (as you see we have other contributors) :-)
